# Generated by Django 3.1 on 2020-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0002_auto_20200820_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='sec_maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.AlterField(
            model_name='primary_revision',
            name='image_url',
            field=models.CharField(max_length=5000000),
        ),
        migrations.AlterField(
            model_name='primary_revision',
            name='std',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondary_revision',
            name='form',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='secondary_revision',
            name='image_url',
            field=models.CharField(max_length=5000000),
        ),
    ]
