# Generated by Django 3.1 on 2020-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0003_auto_20200827_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='pri_std1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='pri_std8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='sec_form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='sec_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='sec_form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.RenameModel(
            old_name='sec_maths',
            new_name='sec_form1',
        ),
    ]
