# Generated by Django 3.1.1 on 2020-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0004_auto_20200827_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
    ]
