# Generated by Django 3.1.1 on 2020-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0005_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='compositionclass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='englishclass8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.DeleteModel(
            name='English',
        ),
        migrations.DeleteModel(
            name='pri_std1',
        ),
        migrations.DeleteModel(
            name='pri_std2',
        ),
        migrations.DeleteModel(
            name='pri_std3',
        ),
        migrations.DeleteModel(
            name='pri_std4',
        ),
        migrations.DeleteModel(
            name='pri_std5',
        ),
        migrations.DeleteModel(
            name='pri_std6',
        ),
        migrations.DeleteModel(
            name='pri_std7',
        ),
        migrations.DeleteModel(
            name='pri_std8',
        ),
        migrations.DeleteModel(
            name='primary_revision',
        ),
        migrations.DeleteModel(
            name='sec_form1',
        ),
        migrations.DeleteModel(
            name='sec_form2',
        ),
        migrations.DeleteModel(
            name='sec_form3',
        ),
        migrations.DeleteModel(
            name='sec_form4',
        ),
        migrations.DeleteModel(
            name='secondary_revision',
        ),
    ]
