# Generated by Django 3.1.1 on 2020-10-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0006_auto_20200926_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compositionclass1',
        ),
        migrations.DeleteModel(
            name='compositionclass2',
        ),
        migrations.DeleteModel(
            name='compositionclass3',
        ),
        migrations.DeleteModel(
            name='englishclass1',
        ),
        migrations.DeleteModel(
            name='englishclass2',
        ),
        migrations.DeleteModel(
            name='englishclass3',
        ),
        migrations.DeleteModel(
            name='englishclass4',
        ),
        migrations.DeleteModel(
            name='englishclass5',
        ),
        migrations.DeleteModel(
            name='englishclass6',
        ),
        migrations.DeleteModel(
            name='englishclass7',
        ),
        migrations.DeleteModel(
            name='englishclass8',
        ),
    ]
