# Generated by Django 3.1.1 on 2020-10-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0007_auto_20201010_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionclass4',
            name='videofile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
