# Generated by Django 3.1.1 on 2020-10-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0009_auto_20201010_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compositionclass4',
        ),
        migrations.DeleteModel(
            name='compositionclass5',
        ),
        migrations.DeleteModel(
            name='compositionclass6',
        ),
        migrations.DeleteModel(
            name='compositionclass7',
        ),
        migrations.DeleteModel(
            name='compositionclass8',
        ),
    ]
