# Generated by Django 3.1.1 on 2020-10-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edurevisions', '0010_auto_20201012_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='compositionclass4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='compositionclass8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
    ]
