# Generated by Django 3.1.1 on 2020-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0011_compositionclass4_compositionclass5_compositionclass6_compositionclass7_compositionclass8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='books/pdf/')),
            ],
        ),
        migrations.DeleteModel(
            name='compositionclass4',
        ),
    ]
