# Generated by Django 3.1.1 on 2020-10-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0012_auto_20201012_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='compositionclass5',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='compositionclass6',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='compositionclass7',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='compositionclass8',
            name='pdf',
            field=models.FileField(upload_to='books/pdfs/'),
        ),
    ]
