# Generated by Django 3.1.1 on 2020-10-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0013_auto_20201012_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='edurevisions/books/pdf/'),
        ),
        migrations.AlterField(
            model_name='compositionclass5',
            name='pdf',
            field=models.FileField(upload_to='books/pdf/'),
        ),
        migrations.AlterField(
            model_name='compositionclass7',
            name='pdf',
            field=models.FileField(upload_to='books/pdf/'),
        ),
        migrations.AlterField(
            model_name='compositionclass8',
            name='pdf',
            field=models.FileField(upload_to='books/pdf/'),
        ),
    ]
