# Generated by Django 3.1.1 on 2020-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edurevisions', '0016_auto_20100101_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='edurevisions/books/pdfs/'),
        ),
    ]
